[defaults]
inventory = "$PROJ_DIR/inventory.csv"
username = "jeremy.schulman"
password = "$NETWORK_PASSWORD"
configs_dir = "$PROJ_DIR/configs"


[[inventory]]
    script = "$PROJ_DIR/netcfgbu/examples/netbox_inventory.py --output inventory.csv"

# -----------------------------------------------------------------------------
#                           Credentials
# -----------------------------------------------------------------------------

[[credentials]]
username = "superadmin"
password = "$ENABLE_PASSWORD"

# -----------------------------------------------------------------------------
#                       Network OS SPecifications
# -----------------------------------------------------------------------------

#[os_specs.eos]
#    disable_paging = "terminal length 0"

[os_name.ios]
    disable_paging = "terminal length 0"

[os_name.nxos]
    show_running = 'show running-config | no-more'

[os_name.asa]
    disable_paging = 'terminal pager 0'

[os_name.aireos]
    show_running = "show run-config commands"
    disable_paging = "config paging disable"
    connection = "netcfgbu.connectors.ssh.LoginPromoptUserPass"

# -----------------------------------------------------------------------------
# Logging - follows Python format as described
#   https://docs.python.org/3/library/logging.config.html
# -----------------------------------------------------------------------------


[logging.loggers.netcfgbu]
    handlers = ["console"]
    level = "INFO"

#[logging.loggers.asyncssh]
#    handlers = ["console"]
#    level = "DEBUG"

[logging.handlers.console]
    class = "logging.StreamHandler"
    formatter = "basic"
    stream = "ext://sys.stdout"

[logging.formatters.basic]
    format = "%(asctime)s %(levelname)s - %(message)s"
