[defaults]
    inventory = "$PROJ_DIR/inventory.csv"
    configs_dir = "$PROJ_DIR/configs"
    credentials.username = "$NETWORK_USERNAME"
    credentials.password = "$NETWORK_PASSWORD"


[[inventory]]
    name = 'netbox'
    script = """\
$PROJ_DIR/netcfgbu/examples/netbox_inventory.py \
    --exclude-tag no-backup \
    --output inventory.csv"""

# -----------------------------------------------------------------------------
#                           Credentials
# -----------------------------------------------------------------------------

#[[credentials]]
#   username = "superadmin"
#   password = "$ENABLE_PASSWORD"

# -----------------------------------------------------------------------------
#                       Network OS Specifications
# -----------------------------------------------------------------------------

# -----------------------------------------------------------------------------
# Cisco switchs, routers, and firewalls
# -----------------------------------------------------------------------------

[os_name.ios]
    disable_paging = "terminal length 0"
    linter = "ios"

[os_name.iosxe]
    linter = 'ios'

[os_name.nxos]
    show_running = 'show running-config | no-more'
    linter = "nxos"

[os_name.iosxr]
    linter = "iosxr"

[os_name.asa]
    disable_paging = 'terminal pager 0'

# -----------------------------------------------------------------------------
# Cisco WLC
# -----------------------------------------------------------------------------

[os_name.aireos]
    # support for 8.5 release requires a special connector to handle the User &
    # Password prompts

    show_running = "show run-config commands"
    disable_paging = "config paging disable"
    connection = "netcfgbu.connectors.ssh.LoginPromptUserPass"

[os_name.aireos8_10]
    # extending the timeout to 3min due to observations with the 8.10 release
    # resulting in sporatic delays in the output of the config.

    timeout = 300

    show_running = "show run-config commands"
    disable_paging = "config paging disable"

    # need to explicitly set the Key Exchange algorithms to support the 8.10
    # SSH configured requirements.

    ssh_configs.kex_algs = [
        'ecdh-sha2-nistp256',
        'diffie-hellman-group14-sha1'
    ]

    [[os_name.aireos8_10.credentials]]
        username = "$WLC_USERNAME"
        password = "$WLC_PASSWORD"

# -----------------------------------------------------------------------------
# Palo Alto PANOS Firewalls
# -----------------------------------------------------------------------------

[os_name.panos]
    disable_paging = [
        "set cli pager off",
        "configure"
    ]
    show_running = "show"
    linter = "panos"

# -----------------------------------------------------------------------------
#                                 Linters
# -----------------------------------------------------------------------------

[linters.iosxr]
    config_starts_after = 'Building configuration'

[linters.ios]
    config_starts_after = 'Current configuration'

[linters.nxos]
    config_starts_after = '!Time:'

[linters.panos]
    config_ends_at = "[edit]"

# -----------------------------------------------------------------------------
# Logging - follows Python format as described
#   https://docs.python.org/3/library/logging.config.html
# -----------------------------------------------------------------------------


[logging.loggers.netcfgbu]
    handlers = ["console", "file"]
    level = "INFO"

#[logging.loggers.asyncssh]
#    handlers = ["console"]
#    level = "DEBUG"

[logging.handlers.console]
    class = "logging.StreamHandler"
    formatter = "basic"
    stream = "ext://sys.stdout"

[logging.handlers.file]
    class = "logging.FileHandler"
    formatter = "basic"
    filename =  "netcfgbu.log"

[logging.formatters.basic]
    format = "%(asctime)s %(levelname)s: %(message)s"
