[defaults]
inventory = "$HOME/Projects/NetworkBackup/inventory.csv"
configs_dir = "$HOME/Projects/NetworkBackup/configs"

[[credentials]]
username = "jeremy.schulman"
password = "$NETWORK_PASSWORD"

[os_specs.eos]
    disable_paging = "terminal length 0"

[os_specs.asa]
    disable_paging = 'terminal pager 0'

[os_specs.aireos]
    show_running = "show run-config commands"
    disable_paging = "config paging disable"
    connection = "netcfgbu.os_specs.ssh.LoginPromoptUserPass"

# -----------------------------------------------------------------------------
# Logging - follows Python format as described
#   https://docs.python.org/3/library/logging.config.html
# -----------------------------------------------------------------------------


#[logging.loggers.netcfgbu2]
#    handlers = ["console"]
#    level = "INFO"

[logging.handlers.console]
    class = "logging.StreamHandler"
    formatter = "basic"
    stream = "ext://sys.stdout"

[logging.formatters.basic]
    format = "%(asctime)s %(levelname)s - %(message)s"
